matrix:
  include:
    
    - language: shell
      os: osx
      osx_image: xcode11.2

      python:
        - 3.6


      install:
        - pip3 install --upgrade pip
        - pip install mysql-connector-python
        - pip install -r requirements.txt
  

      script:
        - cd Backend/
        - ls
        - python3 -m unittest unitTestUserDao.py
        - python3 -m unittest unitTestContainerDao.py
  

    - language: node_js
      node_js: 
        - node
      
      install:
        - npm install newman
      before_script:
        - node --version
        - npm --version
        - node_modules/.bin/newman --version
      
      script: 
        - node_modules/.bin/newman run PostmanTests/Choose2Reuse.postman_environment.json
        - node_modules/.bin/newman run PostmanTests/BackendAPIDoc.postman_collection.json
        
      
  

notifications:
  slack: csc400a-sp21:NFRJA3Yrzv6TnIBprGZlpYWd
  