matrix:
  include:
    
    - language: shell
      os: osx
      osx_image: xcode11.2

      python:
        - 3.6

  
      install: 
        - pip3 install --upgrade pip
        - pip install mysql-connector-python
        - pip install -r requirements.txt

      script:
        - cd Backend/databaseDAOs
        - ls
        - python3 -m unittest testAuthDAO.py
        - python3 -m unittest testLocationDAO.py
        - python3 -m unittest unitTestAuthDAO.py  
        - python3 -m unittest unitTestContainerDAO.py
        - python3 -m unittest unitTestLocationDAO.py
        - python3 -m unittest unitTestRelationshipDAO.py
        - python3 -m unittest unitTestUserDao.py
        - python3 -m unittest unitTestAppInfoDAO.py



    - language: node_js
      node_js: 
        - node
      
      install:
        - npm install newman
      before_script:
        - node --version
        - npm --version
        - node_modules/.bin/newman --version
      
      script: 
        
        - node_modules/.bin/newman run PostmanTests/BackendAPIDoc.postman_collection.json -e PostmanTests/Choose2Reuse.postman_environment.json
        - node_modules/.bin/newman run PostmanTests/UnitTests.postman_collection.json -e PostmanTests/UnitTestingEnvironment.postman_environment.json
        - node_modules/.bin/newman run PostmanTests/AddUserUnitTests.postman_collection.json -d PostmanTests/accountCreationTests.csv




notifications:
  slack: csc400a-sp21:NFRJA3Yrzv6TnIBprGZlpYWd
      
  
