os: osx
osx_image: xcode11.2
language: shell

python:
  - 3.6

install:
  - pip3 install --upgrade pip
  - pip install mysql-connector-python
  - pip install -r requirements.txt

script: 
  - cd Backend/
  - ls
  - python3 -m unittest unitTestUserDao.py
  