name: Choose2Reuse
description: Choose 2 Reuse!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.88+88

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  countdown_flutter: ^0.1.2
  cupertino_icons: ^1.0.0

  http: ^0.12.0
  email_validator: ^1.0.0
  device_info: ^2.0.0
  shared_preferences: ^0.5.1
  intl: ^0.16.1

  firebase_analytics: ^7.1.1
  firebase_core: ^1.0.2
  firebase_messaging: ^9.0.1
  package_info: ^0.4.0+16
  pusher_beams: ^0.5.3+3
  permission_handler: ^6.1.1

dev_dependencies:
  change_app_package_name: ^0.1.2
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.8.0"
  flutter_barcode_scanner: ^1.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/choose2reuse_icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/choose2reuse_logo.jpg
    - assets/images/choose2reuse_icon.jpg
    - assets/images/c2r_reuseIcon_light.jpg
    - assets/images/c2r_reuseIcon_primary.jpg
    - assets/images/c2r_reuseIcon_dark.jpg
    - assets/images/c2r_loading.gif
    - assets/images/sample_qr_code.png
    - assets/images/broken-glass.png
    - assets/images/cookie.gif
    - assets/images/containerPassGif.gif

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages